# Generated by Django 4.2.11 on 2025-10-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_attendance_communicationlog_event_group_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='contact_1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ministry_group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='owner',
        ),
        migrations.AddField(
            model_name='member',
            name='contact_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('Member', 'Member'), ('Pastor', 'Pastor'), ('Staff', 'Staff')], default='Member', max_length=50),
        ),
    ]
